import os, sys, time, colorama
from colorama import Fore
from time import sleep as timeout
def restart_progran():
	os.system(' clear ')
X = str(input(Fore.BLUE+" Type Beens To Start:"))
if 'Beens' or 'Beans' in X:
       os.system(' clear ')
       print(Fore.RED+"                       WHO ARE YOU?                  ")
       time.sleep(0.1)
       print(Fore.RED+"                      :>3qKKKKKKKq3>:                ")
       time.sleep(0.1)
       print(Fore.RED+"                  ';CpKKKKKKKKKKKKKKKpC;'            ")
       time.sleep(0.1)
       print(Fore.RED+"              -iPKKKKKKKKKKKKKKKKKKKKKKKPi-          ")
       time.sleep(0.1)
       print(Fore.RED+"          `~v]KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK]v~`    ")
       time.sleep(0.1)
       print(Fore.RED+"       ,rwKKKKKKKKKKKKKPv;,:'-':,;vPKKKKKKKKKKKKKwr, ")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKKKK/             !KKKKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKKKf               CKKKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKKp-               -qKKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKK>"               "\KKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKw;,_'-                   .-:,wKKKKKKK! ")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKhi*                      KKKKKKKKKKKK ")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKK;                 ;KKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKK2>'             '>2KKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKKKKZ             ZKKKKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKKKKK5             eKKKKKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      !KKKKKKKKKKKqC;-               -;CqKKKKKKKKKKK!")
       time.sleep(0.1)
       print(Fore.RED+"      <KKKKKKKKkr,                       ,rSKKKKKKKK<")
       time.sleep(0.1)
       print(Fore.RED+"       -v]qj;-                             -;jq]v-   ")
       time.sleep(0.1)
       print(Fore.RED+"    Made                 By               @pwn.doxgod")
       time.sleep(1.0)
       os.system(' clear ')  
	  print(" .............................")
	  time.sleep(0.1)
	  print(Fore.MAGENTA+" A HTTP DDOS:    ")
	  time.sleep(0.1)
	  print(" .............................")
	  print(Fore.BLUE+" B Tracking/Doxing: ")
	  time.sleep(0.1)
	  print(" .............................")
	  print(Fore.RED+" C Brute Force:      ")
	  time.sleep(0.1)
	  print(" .............................")
	  print(Fore.MAGENTA+" D Phishing:     ")
	  time.sleep(0.1)
	  print(" .............................")
	  time.sleep(0.1)
	  print(Fore.BLUE+" E Phone# Lookup:   ")
	  time.sleep(0.1)
	  print(" .............................")
	  time.sleep(0.1)
	  print(Fore.RED+" F OSINT:	       ")
	  time.sleep(0.1)
	  print(" .............................")
	  time.sleep(0.1)
	  print(Fore.BLUE+" 0 Exit:	       ")
	  time.sleep(0.1)
	  print(" .............................")
	  A = input(" Beans ==>> ")

	  if A == 'A' or 'a':
	  os.system(' clear ')
	  os.system(' python3 httpddos.py ')

	  if A == 'B' or 'b':
	  	os.system(' clear ')
	  	os.system(' dox.py ')

	  if A == 'C' or 'c':
	  	os.system(' clear ')
	  	os.system(' python3 brute.py ')

	  if A == 'D' or 'd':
	  	os.system(' clear ')
	  	os.system(' python3 phishing.py ')	

	  if A == 'F' or 'f':
	  	os.system(' clear ')
	  	os.system(' python3 osint.py ')

	  if A == 'G' or 'g':
	  	os.system(' clear ')
	  	print(Fore.GREEN+" Goodbye :( ")
	  	sys.exit()
